### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [renatapro/renatax#1]
Dorzucilem pare zmian - rozejrzyj sie co sie zmienilo. Twoim zadaniem bedzie:
- [x] pobrac zmiany do lokalnego repozytorium na Twoim komputerze
- [x] domergowac branch `test` do brancha `master`
- [x] wypchnac zmiany w branchu `master` do repo zdalnego (na githuba)

**Comment by renatapro** [comment]
nie wiem czy dobrze zrobiłam ten merg, chyba coś trochę za dużo rzeczy natworzyłam

**Comment by zdolny** [comment]
wszystko gra, jeden dodatkowy commit widze
